# Site settings
title: "Adventures in Okupi"
email: okupi@cxiu.nl
description: "The most complete history of the world Okupi one will find"
logo_location: "/assets/img/okupi_logo.png"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']
